apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 3
  selector:
  
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]}

  
  template:
    metadata:
      labels:
        
        tier: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
          - containerPort: 80
            